### PR TITLE
Update directory.json

### PR DESCRIPTION
**Pull request by xthegamerx**
Added info about NinuxBO (Bologna -Italy)

### CODE REVIEW

**Comment by andibraeu** [comment]
flons API was meant to list communities on the whole.
i.e. freifunk.net is spreaded into more than 200 communities, also funkfeuer consists of 10 different communities.

my gut instinct would say there should be one entry for ninux, but I'm not in ninux and I don't know how to feel about that.

maybe we should discuss that first @stefanauss @nemesisdesign

**Comment by stefanauss** [comment]
I'm not in freifunk or funkfeuer and I don't know a great deal about those communities, but my educated guess is that we (ninux) are tangibly more fragmented than them.

We actively try to integrate the different communities while still allowing/preserving diversity. This integration works (docs, PR, address space, policies, etc) is also heavily fragmented.

Bologna and Calabria are "Ninux" also by name, but there are WCNs now under the Ninux.org umbrella that were born and are still known by an entirely different name (Eigennet, for instance).

But I believe this is all beside the point. The main reason for these pull requests is to try and get FLONS some traction. For this reason I think it's best to make a single pull request as Ninux-as-a-whole.

**Comment by nemesifier** [comment]
@stefanauss the Freifunk community has hundred of communities: http://freifunk.net/en/how-to-join/find-your-nearest-community/

@andibraeu: I have no strong opinions, is there a general ninux JSON yet? If not we should make that  one first @leeonard @xthegamerx

**Comment by stefanauss** [comment]
@andibraeu if your intention was (or is, for the time being) only to list CN-as-a-whole, then by all means scratch this pull request and also PR #3.

I should mention that I explicitly checked for provisions about this and couldn't find any, and was also confused by the fact that the JSON-spec allowed for granularity in specifying the exact location, which was at odds with CN-as-a-whole entries. Could you perhaps make your intention more clear on the site/generator?

Finally, a pull-request for the whole Ninux was already in the works but got delayed by wrong github permissions for our org, so the local ones went ahead for the reasons above. Apologies!

**Comment by andibraeu** [comment]
The flons API is derrived from the freifunk.net API: https://github.com/freifunk/api.freifunk.net

We discussed about the city field there and we decided to let it in there, because some community networks only cover a city, others i.e. can't even set a country. All fields aren't mandatory, so it shoudn't be a problem.

**Pull request closed without merging**
