### PR TITLE
Added ECN, HUBS and Tegola.

### PR DESCRIPTION
**Pull request by wwaites**
Invented "bgp" for routing. Also invented "asn" to go along
with "networks".

### CODE REVIEW

**Comment by andibraeu** [comment]
Thanks for adding these communities! Are all 3 communities independent?

**Comment by wwaites** [comment]
On Thu, 10 Sep 2015 13:59:25 -0700, Andi Bräu notifications@github.com said:

```
> Thanks for adding these communities! Are all 3 communities
> independent?
```

Independent of what?

HUBS is a co-operative of community networks (though we have started
calling them "collaborative network infrastructure" projects). HUBS
does not provide service to individuals and to join it one needs to be
some sort of community network.

ECN is a member of HUBS in Edinburgh. Tegola is a member of HUBS on
the West Coast of Scotland. ECN and Tegola are independent of each
other. Collectively, as HUBS, they are independent of any carrier or
telephone company.

Technically, on the Internet, these community networks operate as a
confederation. In that sense HUBS is a confederation.

Does this help?

**Comment by andibraeu** [comment]
yes, perfectly :-)

In fact we created that API for "the community as a whole". I.e. in Germany there are more than 200 Freifunk communities. Freifunk is our common community term, our "confederation", so we created 1 entry to this API.

In your case I would then add only the HUBS community to the directory.

**Comment by wwaites** [comment]
I see, that makes sense. I've just updated the PR to only include
HUBS.

**Comment by andibraeu** [comment]
thank you! :+1:

**Comment by ghost** [comment]
> In fact we created that API for "the community as a whole". I.e. in Germany there are more than 200 Freifunk communities. Freifunk is our common community term, our "confederation", so we created 1 entry to this API.

I suggest to state this in the readme, as it seems to be easily
misunderstood (see also the ninux issues).

**Pull request merged**
